#!/bin/bash

# Get the user name from the argument
username=$1

# Run the whoami command under the specified user
su - $username -c "whoami"

# Print the output of the whoami command
echo "The current user is $username"
